
package view;

import controller.ControlePrincipal;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.sql.Connection;
import model.Filme;

public class Tela_principal extends javax.swing.JFrame {
    private ControlePrincipal controle;
    private Filme filmeAtual;
    
    public Tela_principal(model.Usuario usuario, Connection cnn) {
        initComponents();
        controle = new ControlePrincipal(this, usuario, cnn);
        txt_info.setLineWrap(true);
        txt_info.setWrapStyleWord(true);
        
    }
    public void mostrarFilme(model.Filme filme){
        txt_info.setText(filme.getDescricao());//Aparecer a descrição do filme 
        this.filmeAtual = filme;
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagens/" + filme.getImagem()));//Carrega a imagem
        //Ajustar a imagem para caber no label
        Image img = icon.getImage().getScaledInstance(lblCapa.getWidth(), lblCapa.getHeight(), Image.SCALE_SMOOTH);
        
        lblCapa.setIcon(new ImageIcon(img));
        
        btn_curtir.setSelected(controle.verificarInteracao(filme.getNome(), "Curtido"));
        btn_deslike.setSelected(controle.verificarInteracao(filme.getNome(), "Descurtido"));
        btn_favoritar.setSelected(controle.verificarInteracao(filme.getNome(), "Favorito"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_pesquisar = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();
        txt_pesquisa = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btn_favoritos = new javax.swing.JButton();
        btn_curtidos = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btn_hist = new javax.swing.JButton();
        btn_curtir = new javax.swing.JToggleButton();
        btn_deslike = new javax.swing.JToggleButton();
        btn_favoritar = new javax.swing.JToggleButton();
        lblCapa = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_info = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo_FeiTV.png"))); // NOI18N
        jLabel1.setText("FEItv");

        btn_pesquisar.setText("Pesquisar");
        btn_pesquisar.addActionListener(this::btn_pesquisarActionPerformed);

        btn_sair.setBackground(new java.awt.Color(204, 0, 51));
        btn_sair.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btn_sair.setForeground(new java.awt.Color(255, 255, 255));
        btn_sair.setText("Sair");
        btn_sair.addActionListener(this::btn_sairActionPerformed);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Alien");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Batman");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Em alta");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Avatar");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Carros 2");

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Corra");

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Up");

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mario");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Matrix");

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Joker");

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Sherek");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel2)
                        .addComponent(jLabel11)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(15, 15, 15)))
                    .addComponent(jLabel12))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(30, 30, 30)
                .addComponent(jLabel13)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Playlists");

        btn_favoritos.setBackground(new java.awt.Color(204, 0, 0));
        btn_favoritos.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btn_favoritos.setForeground(new java.awt.Color(255, 255, 255));
        btn_favoritos.setText("Favoritos");
        btn_favoritos.addActionListener(this::btn_favoritosActionPerformed);

        btn_curtidos.setBackground(new java.awt.Color(204, 0, 0));
        btn_curtidos.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btn_curtidos.setForeground(new java.awt.Color(255, 255, 255));
        btn_curtidos.setText("Curtidos");
        btn_curtidos.addActionListener(this::btn_curtidosActionPerformed);

        jButton3.setBackground(new java.awt.Color(204, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Descurtidos");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        btn_hist.setBackground(new java.awt.Color(204, 0, 0));
        btn_hist.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn_hist.setForeground(new java.awt.Color(255, 255, 255));
        btn_hist.setText("Histórico");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_hist)
                    .addComponent(jButton3)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_favoritos)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel14))
                        .addComponent(btn_curtidos, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(49, 49, 49))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(39, 39, 39)
                .addComponent(btn_favoritos)
                .addGap(26, 26, 26)
                .addComponent(btn_curtidos)
                .addGap(26, 26, 26)
                .addComponent(jButton3)
                .addGap(27, 27, 27)
                .addComponent(btn_hist)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_curtir.setBackground(new java.awt.Color(0, 0, 0));
        btn_curtir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Icon_like2.png"))); // NOI18N
        btn_curtir.setBorderPainted(false);
        btn_curtir.setContentAreaFilled(false);
        btn_curtir.setFocusPainted(false);
        btn_curtir.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Icon_like.png"))); // NOI18N
        btn_curtir.addActionListener(this::btn_curtirActionPerformed);

        btn_deslike.setBackground(new java.awt.Color(0, 0, 0));
        btn_deslike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Icon_deslike2.png"))); // NOI18N
        btn_deslike.setBorderPainted(false);
        btn_deslike.setContentAreaFilled(false);
        btn_deslike.setFocusPainted(false);
        btn_deslike.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Icon_deslike.png"))); // NOI18N
        btn_deslike.addActionListener(this::btn_deslikeActionPerformed);

        btn_favoritar.setBackground(new java.awt.Color(0, 0, 0));
        btn_favoritar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Icon_favoritar2.png"))); // NOI18N
        btn_favoritar.setBorderPainted(false);
        btn_favoritar.setContentAreaFilled(false);
        btn_favoritar.setFocusPainted(false);
        btn_favoritar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Icon_favoritar.png"))); // NOI18N
        btn_favoritar.addActionListener(this::btn_favoritarActionPerformed);

        txt_info.setEditable(false);
        txt_info.setBackground(new java.awt.Color(0, 0, 0));
        txt_info.setColumns(20);
        txt_info.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txt_info.setForeground(new java.awt.Color(255, 255, 255));
        txt_info.setRows(5);
        txt_info.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_info.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane2.setViewportView(txt_info);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(txt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_pesquisar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(lblCapa, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(btn_curtir, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btn_deslike)
                                .addGap(52, 52, 52)
                                .addComponent(btn_favoritar))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_sair)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btn_sair))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_pesquisar)
                            .addComponent(txt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblCapa, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_deslike)
                            .addComponent(btn_curtir)
                            .addComponent(btn_favoritar))))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarActionPerformed
        controle.pesquisarFilme(txt_pesquisa.getText());
    }//GEN-LAST:event_btn_pesquisarActionPerformed

    private void btn_curtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_curtirActionPerformed
        if(filmeAtual != null){
            if (btn_curtir.isSelected()){
                btn_deslike.setSelected(false);
                
                controle.reagir(filmeAtual.getNome(), "Curtido");
            } else {
                controle.removerInteracao(filmeAtual.getNome(), "Curtido");
            }
        }
    }//GEN-LAST:event_btn_curtirActionPerformed

    private void btn_deslikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deslikeActionPerformed
        if(filmeAtual != null){
            if (btn_deslike.isSelected()){
                btn_curtir.setSelected(false);
                
                controle.reagir(filmeAtual.getNome(), "Descurtido");
            } else {
                controle.removerInteracao(filmeAtual.getNome(), "Descurtido");
            }
        }
    }//GEN-LAST:event_btn_deslikeActionPerformed

    private void btn_favoritarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_favoritarActionPerformed
        if(filmeAtual != null){
            if(btn_favoritar.isSelected()){
                controle.reagir(filmeAtual.getNome(), "Favorito");
            }else{
                controle.removerInteracao(filmeAtual.getNome(), "Favorito");
            }
        }
    }//GEN-LAST:event_btn_favoritarActionPerformed

    private void btn_favoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_favoritosActionPerformed
        Tela_playlist tela = new Tela_playlist("Favorito",controle);
        tela.setVisible(true);
    }//GEN-LAST:event_btn_favoritosActionPerformed

    private void btn_curtidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_curtidosActionPerformed
        Tela_playlist tela = new Tela_playlist("Curtido",controle);
        tela.setVisible(true);
    }//GEN-LAST:event_btn_curtidosActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Tela_playlist tela = new Tela_playlist("Descurtido",controle);
        tela.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        Tela_inicio inicio = new Tela_inicio();
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_sairActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Tela_principal().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_curtidos;
    private javax.swing.JToggleButton btn_curtir;
    private javax.swing.JToggleButton btn_deslike;
    private javax.swing.JToggleButton btn_favoritar;
    private javax.swing.JButton btn_favoritos;
    private javax.swing.JButton btn_hist;
    private javax.swing.JButton btn_pesquisar;
    private javax.swing.JButton btn_sair;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCapa;
    private javax.swing.JTextArea txt_info;
    private javax.swing.JTextField txt_pesquisa;
    // End of variables declaration//GEN-END:variables
}
