/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Controle;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author katym
 */
public class Janela extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Janela.class.getName());

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
        c = new Controle(this);
    }

    public JLabel getLbl1() {
        return Lbl1;
    }

    public void setLbl1(JLabel Lbl1) {
        this.Lbl1 = Lbl1;
    }

    public JLabel getLbl2() {
        return Lbl2;
    }

    public void setLbl2(JLabel Lbl2) {
        this.Lbl2 = Lbl2;
    }

    public JLabel getLbl3() {
        return Lbl3;
    }

    public void setLbl3(JLabel Lbl3) {
        this.Lbl3 = Lbl3;
    }

    public JButton getBt_limpar() {
        return bt_limpar;
    }

    public void setBt_limpar(JButton bt_limpar) {
        this.bt_limpar = bt_limpar;
    }

    public JButton getBt_somar() {
        return bt_somar;
    }

    public void setBt_somar(JButton bt_somar) {
        this.bt_somar = bt_somar;
    }

    public JTextField getTxt_1() {
        return txt_1;
    }

    public void setTxt_1(JTextField txt_1) {
        this.txt_1 = txt_1;
    }

    public JTextField getTxt_2() {
        return txt_2;
    }

    public void setTxt_2(JTextField txt_2) {
        this.txt_2 = txt_2;
    }

    public JTextField getTxt_3() {
        return txt_3;
    }

    public void setTxt_3(JTextField txt_3) {
        this.txt_3 = txt_3;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl1 = new javax.swing.JLabel();
        bt_limpar = new javax.swing.JButton();
        bt_somar = new javax.swing.JButton();
        txt_2 = new javax.swing.JTextField();
        txt_1 = new javax.swing.JTextField();
        txt_3 = new javax.swing.JTextField();
        Lbl2 = new javax.swing.JLabel();
        Lbl3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Soma dois numeros v2");

        Lbl1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Lbl1.setText("Número 1:");

        bt_limpar.setText("Limpar");
        bt_limpar.addActionListener(this::bt_limparActionPerformed);

        bt_somar.setText("Somar");
        bt_somar.addActionListener(this::bt_somarActionPerformed);

        txt_2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        txt_2.addActionListener(this::txt_2ActionPerformed);

        txt_1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        txt_1.addActionListener(this::txt_1ActionPerformed);

        txt_3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        txt_3.addActionListener(this::txt_3ActionPerformed);

        Lbl2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Lbl2.setText("Número 2:");

        Lbl3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Lbl3.setText("Resultado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txt_2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lbl2)
                                    .addComponent(Lbl3)
                                    .addComponent(Lbl1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(bt_limpar)
                                .addGap(48, 48, 48)
                                .addComponent(bt_somar)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(txt_3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(348, 348, 348))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl1)
                    .addComponent(txt_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl2)
                    .addComponent(txt_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl3))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_limpar)
                    .addComponent(bt_somar))
                .addContainerGap(249, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_2ActionPerformed

    private void txt_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_1ActionPerformed

    private void txt_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_3ActionPerformed

    private void bt_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limparActionPerformed
        // TODO add your handling code here:
        c.controleLimpar();
    }//GEN-LAST:event_bt_limparActionPerformed

    private void bt_somarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_somarActionPerformed
        // TODO add your handling code here:
        c.controleSomar();
    }//GEN-LAST:event_bt_somarActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Janela().setVisible(true));
//    }
    
    private Controle c; 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl1;
    private javax.swing.JLabel Lbl2;
    private javax.swing.JLabel Lbl3;
    private javax.swing.JButton bt_limpar;
    private javax.swing.JButton bt_somar;
    private javax.swing.JTextField txt_1;
    private javax.swing.JTextField txt_2;
    private javax.swing.JTextField txt_3;
    // End of variables declaration//GEN-END:variables
}
